### ISSUE TITLE
has_key removed from Python 3

### ISSUE THREAD

**Issue by sginsbourg** [dmonego/har2jmeter#1]
Traceback (most recent call last):
  File "har2jmeter.py", line 40, in <module>
    har2jmeter(fname)
  File "har2jmeter.py", line 14, in har2jmeter
    urls = [urlparts(entry['request']) for entry in harentries]
  File "har2jmeter.py", line 14, in <listcomp>
    urls = [urlparts(entry['request']) for entry in harentries]
  File "har2jmeter.py", line 22, in urlparts
    host_arr = [h['value'] for h in harrequest['headers'] if (h.has_key('name') and h['name'] == 'Host')]
  File "har2jmeter.py", line 22, in <listcomp>
    host_arr = [h['value'] for h in harrequest['headers'] if (h.has_key('name') and h['name'] == 'Host')]
AttributeError: 'dict' object has no attribute 'has_key'

**Comment by dmonego** [comment]
Thanks for the bug report. It was an easy fix, so you should be able to make it work with the latest.

**Comment by sginsbourg** [comment]
# coding=UTF-8

import sys, jinja2, json, codecs, re

from jinja2 import Environment, PackageLoader

def har2jmeter(harfile):
    hardata = codecs.open(harfile, 'r', 'utf-8').read()
    har = json.loads(hardata)
    harentries = har['log']['entries']

    urls = [urlparts(entry['request']) for entry in harentries]
    urls = [url for url in urls if not url is None]
    env = Environment(loader=PackageLoader(__name__, 'templates'))
    template = env.get_template('jmeter.jinja')

    print(template.render(urls=urls))

def urlparts(harrequest):
    host_arr = [h['value'] for h in harrequest['headers'] if ('name' in h and h['name'] == 'Host')]
    if len(host_arr) == 1:
        host = host_arr[0]
    else:
        return None
    url = harrequest['url']
    get_parts = url.split('?')
    if len(get_parts) > 1:
        url = get_parts[0]
        params = dict([p.split('=') for p in get_parts[1].split("&")])
    else:
        params = {}
    pathstart = re.search(host, url).end() 
    path = url[pathstart:]
    return {'url': url, 'host': host, 'path': path, 'params':params}

if __name__ == '__main__':
    fname = sys.argv[1]
    har2jmeter(fname)

**Comment by sginsbourg** [comment]
FIXED

**Comment by sginsbourg** [comment]
Fixed:

The dict.has_key() method deprecated in favor of the in operator, is no longer available in Python 3.
Instead of:	h.has_key('name')
#you should use:	'name' in h

coding=UTF-8
import sys, jinja2, json, codecs, re

from jinja2 import Environment, PackageLoader

def har2jmeter(harfile):
hardata = codecs.open(harfile, 'r', 'utf-8').read()
har = json.loads(hardata)
harentries = har['log']['entries']

urls = [urlparts(entry['request']) for entry in harentries]
urls = [url for url in urls if not url is None]
env = Environment(loader=PackageLoader(__name__, 'templates'))
template = env.get_template('jmeter.jinja')

print(template.render(urls=urls))
def urlparts(harrequest):
host_arr = [h['value'] for h in harrequest['headers'] if ('name' in h and h['name'] == 'Host')]
if len(host_arr) == 1:
host = host_arr[0]
else:
return None
url = harrequest['url']
get_parts = url.split('?')
if len(get_parts) > 1:
url = get_parts[0]
params = dict([p.split('=') for p in get_parts[1].split("&")])
else:
params = {}
pathstart = re.search(host, url).end()
path = url[pathstart:]
return {'url': url, 'host': host, 'path': path, 'params':params}

if name == 'main':
fname = sys.argv[1]
har2jmeter(fname)
